CREATE SEQUENCE SEQ_PRINCIPI_ATTIVI INCREMENT BY 1 START WITH 0;
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Altro');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Aciclovir');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Acido alendronico');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Acido clodronico');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Acido pipemidico');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Acido tranexamico');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Acido ursodesossicolico');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Acido valproico (sale di sodio)');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Acqua per preparazioni iniettabili');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Adrenalina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Alfuzosina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Allopurinolo');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Amikacina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Amiodarone');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Amisulpride');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Amlodipina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Amoxicillina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Amoxicillina + Acido clavulanico');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Ampicillina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Ampicillina + Sulbactam');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Atenololo');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Atenololo + Clortalidone');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Atropina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Azatioprina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Azitromicina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Bacampicillina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Baclofene');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Beclometasone');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Benazepril');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Benazepril + Idroclorotiazide');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Benzilpenicillina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Benzilpenicillina benzatina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Betametasone');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Bezafibrato');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Bicalutamide');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Bisoprololo');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Brimonidina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Bromocriptina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Budesonide');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Cabergolina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Calcio carbonato');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Calcio carbonato + Colecalciferolo');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Calcio fosfato + Colecalciferolo');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Calcipotriolo');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Calcitonina sintetica di salmone');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Calcitriolo');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Captopril');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Captopril + Idroclorotiazide');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Carbamazepina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Carvedilolo');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Cefaclor');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Cefadroxil');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Cefalexina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Cefalotina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Cefamandolo');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Cefatrizina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Cefazolina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Cefixima');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Cefonicid');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Cefoperazone');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Cefotaxima');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Ceftazidima');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Ceftriaxone');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Cefuroxima');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Cetirizina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Cimetidina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Ciprofloxacina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Ciproterone');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Ciproterone + Etinilestradiolo');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Citalopram');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Claritromicina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Clindamicina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Clobetasolo');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Clomipramina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Clopidogrel');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Clorochina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Clozapina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Deferoxamina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Desmopressina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Diclofenac');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Diltiazem');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Dorzolamide');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Dorzolamide + Timololo');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Doxazosin');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Doxiciclina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Enalapril');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Enalapril + Idroclorotiazide');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Eparina calcica');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Eparina sodica');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Eritromicina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Estradiolo');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Etinilestradiolo');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Etinilestradiolo + Gestodene');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Famciclovir');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Famotidina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Felodipina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Fenofibrato');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Ferroso gluconato');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Fexofenadina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Finasteride');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Flecainide');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Flucloxacillina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Fluconazolo');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Flunisolide');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Fluocinolone acetonide');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Fluoxetina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Flurbiprofene');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Flutamide');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Fluvastatina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Fluvoxamina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Formoterolo');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Fosfomicina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Fosinopril');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Fosinopril + Idroclorotiazide');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Furosemide');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Gabapentin');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Gemfibrozil');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Gentamicina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Glicerina fenica');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Gliclazide');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Glimepiride');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Glucosio');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Granisetrone');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Griseofulvina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Ibuprofene');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Idroclorotiazide');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Imipramina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Indapamide');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Isoniazide');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Isosorbide mononitrato');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Isotretinoina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Itraconazolo');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Josamicina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Ketoprofene');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Ketorolac');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Ketotifene');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Lamotrigina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Lansoprazolo');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Latanoprost');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Lercanidipina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Levocetirizina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Levodopa + Benserazide');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Levodopa + Carbidopa');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Lisinopril');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Lisinopril + Idroclorotiazide');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Lisinopril+Idroclorotiazide');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Litio carbonato');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Loratadina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Losartan');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Losartan + Idroclorotiazide');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Megestrolo');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Meloxicam');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Mesalazina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Metformina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Metformina + Glibenclamide');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Metilergometrina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Metoclopramide');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Metoprololo');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Metotrexato');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Metronidazolo');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Mirtazapina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Moxonidina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Naloxone');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Naprossene');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Nebivololo');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Nicardipina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Nifedipina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Nimesulide');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Nitroglicerina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Nomegestrolo');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Norfloxacina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Octreotide');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Omeprazolo');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Ondansetrone');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Ossibutinina cloridrato');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Pantoprazolo');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Paroxetina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Pergolide');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Perindopril');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Perindopril + Indapamide');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Pilocarpina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Piperacillina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Piperacillina + Tazobactan');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Piroxicam');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Potassio canrenoato');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Pramipexolo');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Pravastatina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Propafenone');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Protamina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Quinapril');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Quinapril + Idroclorotiazide');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Ramipril');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Ramipril + Idroclorotiazide');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Ranitidina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Repaglinide');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Ribavirina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Rifampicina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Rifaximina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Risperidone');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Ropinirolo');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Salbutamolo');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Salbutamolo + Ipratropio bromuro');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Scopolamina butilbromuro');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Sertralina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Simvastatina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Sodio cloruro');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Sodio Risedronato');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Sotalolo');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Spiramicina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Streptomicina solfato');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Sucralfato');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Sulfadiazina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Sumatriptan');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Tamoxifene');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Tamsulosina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Tenoxicam');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Terazosina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Terbinafina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Ticlopidina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Timololo');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Tobramicina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Torasemide');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Trandolapril');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Valaciclovir');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Venlafaxina');
INSERT INTO PRINCIPI_ATTIVI (CODICE, DESCRIZIONE) VALUES (seq_principi_attivi.nextval, 'Verapamil');
