SET DEFINE OFF;
UPDATE CONF SET CONF_TXT = 'Vers. 16.01e' WHERE CONF_KPROC = 'SINS' AND CONF_KEY = 'VERSIONE';

ALTER TABLE RM_INTOLLERANZE_ALLERGIE ADD (ALTRO_PRINCIPIO_ATTIVO VARCHAR2(200 BYTE));

COMMIT;

