
SET DEFINE ON;
-- PID PROCEDURA  SINSSNT WEB2 
DEFINE VAR_ISAS_PID=&ENTER_ISAS_PID_PER_SINSSNT; 
-- PROFILO
DEFINE VAR_ISAS_PROFID=&ENTER_ISAS_PROFID;

-- FLUSSI SIAD MODIFICARE DISTRETTO
INSERT INTO isas_procprof VALUES (&var_isas_pid., &var_isas_profid., 'FLUXMINS', 'MODI', 1, SYSDATE);
-- FLUSSI FL21 MODIFICARE DISTRETTO
INSERT INTO isas_procprof VALUES (&var_isas_pid., &var_isas_profid., 'FLSFL21S', 'MODI', 1, SYSDATE);

COMMIT; 