
SET DEFINE OFF;
ALTER TABLE PRESIDI_TAB DROP COLUMN RCT_COD_TIPOPRES;
ALTER TABLE PRESIDI_TAB DROP COLUMN RCT_STRUTTURA_RICOVERO;
update presidi_tab set aster_tipopres='9'
where tipo_ass1<>'S09';
COMMIT;
