REM INSERTING into PRESTAZ_BISOGNI
SET DEFINE OFF;

Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA) values (SEQ_PRESTAZ_BISOGNI.nextVal,'FIS16', 'CP_ARD','-1',null);
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA) values (SEQ_PRESTAZ_BISOGNI.nextVal,'FIS101','CP_ARD','3',null);
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA) values (SEQ_PRESTAZ_BISOGNI.nextVal,'FIS106','CP_ARD','3',null);
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA) values (SEQ_PRESTAZ_BISOGNI.nextVal,'FIS121','CP_ARD','7',null);
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA) values (SEQ_PRESTAZ_BISOGNI.nextVal,'FIS102','CP_ARD','3',null);
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA) values (SEQ_PRESTAZ_BISOGNI.nextVal,'FIS103','CP_ARD','3',null);
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA) values (SEQ_PRESTAZ_BISOGNI.nextVal,'FIS139','CP_ARD','3',null);

Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF73','CP_AID','3',null);
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF74','CP_AID','3',null);
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF18','CP_AID','-1',null);
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF54','CP_AID','3',null);
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF78','CP_AID','3',null);
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF80','CP_AID','3',null);
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF19','CP_AID','-1',null);
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF81','CP_AID','3',null);
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF84','CP_AID','3',null);

--update prestaz_bisogni set BISOGNO = 'CP_AID' where Bisogno = 'CP_ARD'
--update prestaz_bisogni set BISOGNO = 'CP_ARD' where Bisogno = 'CP_AID' and prest_cod like 'FIS%'
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA) values (SEQ_PRESTAZ_BISOGNI.nextVal,'MMG143','CP_ADP','3',null); 
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA) values (SEQ_PRESTAZ_BISOGNI.nextVal,'MMG2',  'CP_ADP',null,null);
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA) values (SEQ_PRESTAZ_BISOGNI.nextVal,'MMG20', 'CP_ADP',null,null);
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA) values (SEQ_PRESTAZ_BISOGNI.nextVal,'MMG30', 'CP_ADP',null,null);
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA) values (SEQ_PRESTAZ_BISOGNI.nextVal,'MMG36', 'CP_ADP',null,null);
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA) values (SEQ_PRESTAZ_BISOGNI.nextVal,'MMG37', 'CP_ADP',null,null);
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA) values (SEQ_PRESTAZ_BISOGNI.nextVal,'MMG6',  'CP_ADP',null,null);
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA) values (SEQ_PRESTAZ_BISOGNI.nextVal,'MMG82', 'CP_ADP',null,null);
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA) values (SEQ_PRESTAZ_BISOGNI.nextVal,'MMG86', 'CP_ADP',null,null);
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA) values (SEQ_PRESTAZ_BISOGNI.nextVal,'MMG9',  'CP_ADP',null,null);
