drop sequence SEQ_PRESTAZ_BISOGNI;
CREATE SEQUENCE SEQ_PRESTAZ_BISOGNI START WITH 1;

ALTER TABLE PRESTAZ_BISOGNI 
ADD (PREST_DES CHAR(30) );

REM INSERTING into PRESTAZ_BISOGNI
SET DEFINE OFF;

Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'MMG2','DEFAULT','3',null,null);

-- 1 autonomia
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF15','AUTONOMIA2','3',null,null);
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF16','AUTONOMIA2','3',null,null);
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF4','AUTONOMIA2','3',null,null);

--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'FIS16','AUTONOMIA2','3',null,null);
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF138','AUTONOMIA2','3',null,null);
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'FIS138','AUTONOMIA2','3',null,null);
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF15','AUTONOMIA3','3',null,null);
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF16','AUTONOMIA3','3',null,null);
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF138','AUTONOMIA3','3',null,null);
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF4','AUTONOMIA3','3',null,null);
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'FIS16','AUTONOMIA3','3',null,null);
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'FIS138','AUTONOMIA3','3',null,null);

--2 RIABILITAZIONE
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'FIS106','RIAB_NEUROLOGICA','3',null,'RECUP ABIL ATTIV QUOTIDIANE   ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'FIS16','RIAB_NEUROLOGICA','-1',null,'EDUC CG CORRETTA MOB/POST     ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'FIS121','RIAB_NEUROLOGICA','7',null,'ESECUZ TEST/SCALE DI VALUTAZ  ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'LOG105','RIAB_NEUROLOGICA','3',null,'');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'LOG11' ,'RIAB_AFASIA','3',null,'');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'LOG10' ,'RIAB_AFASIA','3',null,'');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'LOG104','RIAB_AFASIA','3',null,'');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'LOG129','RIAB_AFASIA','3',null,'');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'FIS106','RIAB_ORTPEDICA','3',null,'RECUP ABIL ATTIV QUOTIDIANE   ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'FIS101','RIAB_ORTPEDICA','3',null,'TRATTAM RIEDUCAZ MOTORIA      ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'FIS16','RIAB_ORTPEDICA','-1',null,'EDUC CG CORRETTA MOB/POST     ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'FIS121','RIAB_ORTPEDICA','7',null,'ESECUZ TEST/SCALE DI VALUTAZ  ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'FIS106','RIAB_MANTENIMENTO','3',null,'RECUP ABIL ATTIV QUOTIDIANE   ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'FIS101','RIAB_MANTENIMENTO','3',null,'TRATTAM RIEDUCAZ MOTORIA      ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'FIS16','RIAB_MANTENIMENTO','-1',null,'EDUC CG CORRETTA MOB/POST     ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'FIS121','RIAB_MANTENIMENTO','7',null,'ESECUZ TEST/SCALE DI VALUTAZ  ');

--3 APPARATO RESPIRATORIO
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'FIS102','RESP_TOSSE_SECR','3',null,'RIEDUCAZIONE RESPIRATORIA     ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'FIS103','RESP_TOSSE_SECR','3',null,'RIEDUCAZIONE TOSSE ASSISTITIA ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF139','RESP_TOSSE_SECR','3',null,'POSIZIONAMENTO POSTURALE      ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF149','RESP_TOSSE_SECR','3',null,'');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'FIS139','RESP_TOSSE_SECR','3',null,'POSIZIONAMENTO POSTURALE      ');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF27' ,'RESP_TOSSE_SECR','-1',null,'EDUC CG TRACHEO/BRONCOASPIRAZ ');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF140','RESP_TOSSE_SECR','3',null,'PREL ARTERIO PER EMOGASANALISI');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF58','RESP_TOSSE_SECR','3',null,'GESTIONE TRACHEOSTOMIA        ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF139','RESP_OSSIGENOTERAPIA','3',null,'POSIZIONAMENTO POSTURALE      ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'FIS102','RESP_OSSIGENOTERAPIA','3',null,'RIEDUCAZIONE RESPIRATORIA     ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'FIS103','RESP_OSSIGENOTERAPIA','3',null,'RIEDUCAZIONE TOSSE ASSISTITIA ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF140','RESP_OSSIGENOTERAPIA','3',null,'PREL ARTERIO PER EMOGASANALISI');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'FIS139','RESP_OSSIGENOTERAPIA','3',null,'POSIZIONAMENTO POSTURALE      ');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF27','RESP_OSSIGENOTERAPIA','-1',null,'EDUC CG TRACHEO/BRONCOASPIRAZ ');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF58','RESP_OSSIGENOTERAPIA','3',null,'GESTIONE TRACHEOSTOMIA        ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF27','RESP_VENTILOTERAPIA','-1',null,'EDUC CG TRACHEO/BRONCOASPIRAZ ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF140','RESP_VENTILOTERAPIA','3',null,'PREL ARTERIO PER EMOGASANALISI');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'FIS139','RESP_VENTILOTERAPIA','3',null,'POSIZIONAMENTO POSTURALE      ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF149','RESP_VENTILOTERAPIA','3',null,'');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'FIS102','RESP_VENTILOTERAPIA','3',null,'RIEDUCAZIONE RESPIRATORIA     ');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'FIS103','RESP_VENTILOTERAPIA','3',null,'RIEDUCAZIONE TOSSE ASSISTITIA ');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF139','RESP_VENTILOTERAPIA','3',null,'POSIZIONAMENTO POSTURALE      ');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF58','RESP_VENTILOTERAPIA','3',null,'GESTIONE TRACHEOSTOMIA        ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'FIS102','RESP_PORTATORE_TRACHEO','3',null,'RIEDUCAZIONE RESPIRATORIA     ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF27','RESP_PORTATORE_TRACHEO','-1',null,'EDUC CG TRACHEO/BRONCOASPIRAZ ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF140','RESP_PORTATORE_TRACHEO','3',null,'PREL ARTERIO PER EMOGASANALISI');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF58','RESP_PORTATORE_TRACHEO','3',null,'GESTIONE TRACHEOSTOMIA        ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'FIS139','RESP_PORTATORE_TRACHEO','3',null,'POSIZIONAMENTO POSTURALE      ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF149','RESP_PORTATORE_TRACHEO','3',null,'');--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'FIS103','RESP_PORTATORE_TRACHEO','3',null,'RIEDUCAZIONE TOSSE ASSISTITIA ');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF139','RESP_PORTATORE_TRACHEO','3',null,'POSIZIONAMENTO POSTURALE      ');

--4 STATO NUTRIZIONALE
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'MMG65','NUTR_DIMAGRIMENTO','-1',null,'FORMULAZ DIETA PERSONALIZZATA ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF69','NUTR_DIMAGRIMENTO','3',null,'ISTRUZ PREP DIETE CONSIST MODI');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'MMG66','NUTR_DIMAGRIMENTO','3',null,'VALUTAZIONE DELLA DISFAGIA    ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF67','NUTR_DIMAGRIMENTO','3',null,'IMP/MON PROG NUTRIZ ARTIF ENTE');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF70','NUTR_DIMAGRIMENTO','-1',null,'ISTRUZ SOMM PASTI POST FACIL  ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF47','NUTR_DIMAGRIMENTO','3',null,'ASSIST/GEST POMPA INFUSIONALE ');

Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'MMG64','NUTR_DISFAGIA','-1',null,'ANAMNESI DIETOLOGICA          ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF69','NUTR_DISFAGIA','3',null,'ISTRUZ PREP DIETE CONSIST MODI');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'DIE70','NUTR_DISFAGIA','-1',null,'ISTRUZ SOMM PASTI POST FACIL  ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'MMG66','NUTR_DISFAGIA','3',null,'VALUTAZIONE DELLA DISFAGIA    ');

--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF66','NUTR_DISFAGIA','3',null,'VALUTAZIONE DELLA DISFAGIA    ');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF66','NUTR_DISIDRATAZIONE','3',null,'VALUTAZIONE DELLA DISFAGIA    ');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'DIE67','NUTR_DIMAGRIMENTO','3',null,'IMP/MON PROG NUTRIZ ARTIF ENTE');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'DIE67','NUTR_DISFAGIA','3',null,'IMP/MON PROG NUTRIZ ARTIF ENTE');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'DIE67','NUTR_DISIDRATAZIONE','3',null,'IMP/MON PROG NUTRIZ ARTIF ENTE');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF67','NUTR_DISFAGIA','3',null,'IMP/MON PROG NUTRIZ ARTIF ENTE');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF67','NUTR_DISIDRATAZIONE','3',null,'IMP/MON PROG NUTRIZ ARTIF ENTE');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF68','NUTR_DIMAGRIMENTO','3',null,'IMP/MON PROG NUTRIZ ARTIF PARE');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF68','NUTR_DISFAGIA','3',null,'IMP/MON PROG NUTRIZ ARTIF PARE');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF68','NUTR_DISIDRATAZIONE','3',null,'IMP/MON PROG NUTRIZ ARTIF PARE');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF71','NUTR_DIMAGRIMENTO','3',null,'POSIZ/SOSTITUZ SNG            ');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF71','NUTR_DISFAGIA','3',null,'POSIZ/SOSTITUZ SNG            ');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF71','NUTR_DISIDRATAZIONE','3',null,'POSIZ/SOSTITUZ SNG            ');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF69','NUTR_DISIDRATAZIONE','3',null,'ISTRUZ PREP DIETE CONSIST MODI');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'DIE69','NUTR_DIMAGRIMENTO','3',null,'ISTRUZ PREP DIETE CONSIST MODI');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'DIE69','NUTR_DISFAGIA','3',null,'ISTRUZ PREP DIETE CONSIST MODI');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'DIE69','NUTR_DISIDRATAZIONE','3',null,'ISTRUZ PREP DIETE CONSIST MODI');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF70','NUTR_DISFAGIA','-1',null,'ISTRUZ SOMM PASTI POST FACIL  ');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF70','NUTR_DISIDRATAZIONE','-1',null,'ISTRUZ SOMM PASTI POST FACIL  ');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'DIE70','NUTR_DIMAGRIMENTO','-1',null,'ISTRUZ SOMM PASTI POST FACIL  ');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'DIE70','NUTR_DISIDRATAZIONE','-1',null,'ISTRUZ SOMM PASTI POST FACIL  ');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF111','NUTR_DISIDRATAZIONE','3',null,'ISTRUZ GEST DOM NUTRIZ ENTER  ');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'DIE111','NUTR_DIMAGRIMENTO','3',null,'ISTRUZ GEST DOM NUTRIZ ENTER  ');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'DIE111','NUTR_DISFAGIA','3',null,'ISTRUZ GEST DOM NUTRIZ ENTER  ');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'DIE111','NUTR_DISIDRATAZIONE','3',null,'ISTRUZ GEST DOM NUTRIZ ENTER  ');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF112','NUTR_DIMAGRIMENTO','3',null,'ISTRUZ GEST SONDA NUTRIZIONALE');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF112','NUTR_DISFAGIA','3',null,'ISTRUZ GEST SONDA NUTRIZIONALE');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF112','NUTR_DISIDRATAZIONE','3',null,'ISTRUZ GEST SONDA NUTRIZIONALE');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'DIE112','NUTR_DIMAGRIMENTO','3',null,'ISTRUZ GEST SONDA NUTRIZIONALE');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'DIE112','NUTR_DISFAGIA','3',null,'ISTRUZ GEST SONDA NUTRIZIONALE');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'DIE112','NUTR_DISIDRATAZIONE','3',null,'ISTRUZ GEST SONDA NUTRIZIONALE');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF73','NUTR_DIMAGRIMENTO','3',null,'GESTIONE SNG                  ');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF73','NUTR_DISFAGIA','3',null,'GESTIONE SNG                  ');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF73','NUTR_DISIDRATAZIONE','3',null,'GESTIONE SNG                  ');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF74','NUTR_DIMAGRIMENTO','3',null,'GESTIONE PEG/PEJ              ');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF74','NUTR_DISFAGIA','3',null,'GESTIONE PEG/PEJ              ');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF74','NUTR_DISIDRATAZIONE','3',null,'GESTIONE PEG/PEJ              ');

--5 APPARATO GASTROINTESTINALE
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF81','GASTR_STIPSI','3',null,'GEST ALVO(INT EDUC IGIEN-ALIM)');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF82','GASTR_STIPSI','3',null,'');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF81','GASTR_INCONT','3',null,'GEST ALVO(INT EDUC IGIEN-ALIM)');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF81','GASTR_VOMITO','3',null,'GEST ALVO(INT EDUC IGIEN-ALIM)');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF84','GASTR_STOMIA','3',null,'GESTIONE ENTEROSTOMIE         ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF19','GASTR_STOMIA','-1',null,'EDUC CG GESTIONE ENTEROSTOMIE ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF81','GASTR_STOMIA','3',null,'GEST ALVO(INT EDUC IGIEN-ALIM)');

-- 6 APPARATO GENITOURINARIO
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF18','GENURI_INCONT','-1',null,'EDUC CG GEST DERIVAZ URINAR   ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF78','GENURI_CATETERISMO','3',null,'POSIZ/SOST/GEST CATET VESCIC  ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF80','GENURI_UROSTOMIA','3',null,'GEST CAT SOVRAPUB/ALTRE DER UR');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF18','GENURI_UROSTOMIA','-1',null,'EDUC CG GEST DERIVAZ URINAR   ');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF18','GENURI_EMATURIA','-1',null,'EDUC CG GEST DERIVAZ URINAR   ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF54','GENURI_DIALISI','3',null,'IMPOSTAZ DIALISI PERITONEALE  ');


-- 7 APPARATO TEGUMENTARIO
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF86','CUTE_ULCERE12','3',null,'MEDICAZIONI SEMPLICI          ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF90','CUTE_ULCERE12','3',null,'TOILETTE LESIONE/FERITA SUPERF');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF87','CUTE_ULCERE34','3',null,'MEDICAZIONI COMPLESSE         ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF91','CUTE_ULCERE34','3',null,'TOILETTE LESIONE/FERITA PROFON');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF113','CUTE_ULCERE34','3',null,'COURETTAGE CHIRURGICO         ');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'MMG99','CUTE_PRESSIONE','3',null,'SUTURA FERITE                 ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'MMG99','CUTE_LACERAZIONI','3',null,'SUTURA FERITE                 ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF100','CUTE_LACERAZIONI','-1',null,'RIMOZ PUNTI/GRAFF DI SUTURA   ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF92','CUTE_ALTRO','3',null,'COURETT/RIMOZ UNGHIA/MATR UNG ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF114','CUTE_ALTRO','3',null,'BENDAGGIO ELASTOCOMPRESSIVO   ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF88','CUTE_ALTRO','3',null,'BENDAGGIO CON DOCCIA IMMOBIL  ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF89','CUTE_ALTRO','3',null,'FASC SEMPL, BEND, BEND ADES EL');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'MMG99','CUTE_CURA','3',null,'SUTURA FERITE                 ');


-- 11	ONCOLOGICO/TERMINALE
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF46','ONCO_TERM_NON_ONCO','3',null,'GEST CATET VEN CENTR/PORTACATH');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF48','ONCO_TERM_NON_ONCO','3',null,'GESTIONE CATETERI SPINALI     ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'PSI137','ONCO_TERM_NON_ONCO','-1',null,'COLL SOSTEGNO/ELABORAZ LUTTO  ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'PSI32','ONCO_TERM_NON_ONCO','3',null,'SUPPORTO PSICO PER IL PAZIENTE');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'PSI33','ONCO_TERM_NON_ONCO','3',null,'SUPPORTO PSICO PER LA FAMIGLIA');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF21','ONCO_TERM_NON_ONCO','-1',null,'EDUC CG GEST DISP SOMM FARM   ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF47','ONCO_TERM_NON_ONCO','3',null,'ASSIST/GEST POMPA INFUSIONALE ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'MMG35','ONCO_TERM_NON_ONCO','-1',null,'PRESCRIZIONE TERAPEUTICA      ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF46','ONCO_TERM_ONCO','3',null,'GEST CATET VEN CENTR/PORTACATH');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'PSI137','ONCO_TERM_ONCO','-1',null,'COLL SOSTEGNO/ELABORAZ LUTTO  ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF21','ONCO_TERM_ONCO','-1',null,'EDUC CG GEST DISP SOMM FARM   ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF47','ONCO_TERM_ONCO','3',null,'ASSIST/GEST POMPA INFUSIONALE ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'PSI32','ONCO_TERM_ONCO','3',null,'SUPPORTO PSICO PER IL PAZIENTE');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'PSI33','ONCO_TERM_ONCO','3',null,'SUPPORTO PSICO PER LA FAMIGLIA');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'MMG35','ONCO_TERM_ONCO','-1',null,'PRESCRIZIONE TERAPEUTICA      ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF48','ONCO_TERM_ONCO','3',null,'GESTIONE CATETERI SPINALI     ');


Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF46','ONCO_ONCOLOGICO','3',null,'GEST CATET VEN CENTR/PORTACATH');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'MMG35','ONCO_ONCOLOGICO','-1',null,'PRESCRIZIONE TERAPEUTICA      ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF21','ONCO_ONCOLOGICO','-1',null,'EDUC CG GEST DISP SOMM FARM   ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'PSI32','ONCO_ONCOLOGICO','3',null,'SUPPORTO PSICO PER IL PAZIENTE');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'PSI33','ONCO_ONCOLOGICO','3',null,'SUPPORTO PSICO PER LA FAMIGLIA');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'PSI137','ONCO_ONCOLOGICO','-1',null,'COLL SOSTEGNO/ELABORAZ LUTTO  ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF48','ONCO_ONCOLOGICO','3',null,'GESTIONE CATETERI SPINALI     ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF47','ONCO_ONCOLOGICO','3',null,'ASSIST/GEST POMPA INFUSIONALE ');

Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'MMG35','ONCO_CHEMIOTERAPIA','-1',null,'PRESCRIZIONE TERAPEUTICA      ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF47','ONCO_CHEMIOTERAPIA','3',null,'ASSIST/GEST POMPA INFUSIONALE ');

Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'MMG35','ONCO_RADIOTERAPIA','-1',null,'PRESCRIZIONE TERAPEUTICA      ');

Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF42','ONCO_DOLORE','3',null,'TERAPIA INIETT VIA EPID/SPIN  ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF47','ONCO_DOLORE','3',null,'ASSIST/GEST POMPA INFUSIONALE ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF48','ONCO_DOLORE','3',null,'GESTIONE CATETERI SPINALI     ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'MMG35','ONCO_DOLORE','-1',null,'PRESCRIZIONE TERAPEUTICA      ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF46','ONCO_DOLORE','3',null,'GEST CATET VEN CENTR/PORTACATH');

-- 12	PRESTAZIONI
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'MMG141','PREST_PRELIEVO','-1',null,'PRESCRIZIONE PRELIEVO EMATICO ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'MMG142','PREST_PRELIEVO','-1',null,'PRESCRIZ PRELIEVO SANGUE CAPIL');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'MMG143','PREST_PRELIEVO','3',null,'PRESCR ESEC INDAG BIOUM ROUT  ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF7','PREST_PRELIEVO','3',null,'');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF140','PREST_PRELIEVO','3',null,'PREL ARTERIO PER EMOGASANALISI');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF8','PREST_PRELIEVO','3',null,'PRELIEVO EMATICO CAPILLARE    ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF6','PREST_PRELIEVO','3',null,'PRELIEVO EMATICO              ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'MMG144','PREST_ECG','-1',null,'PRESCRIZIONE ECG              ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF9','PREST_ECG','-1',null,'ECG                           ');
--Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF44','PREST_TELEMETRIA','3',null,'POSIZ CATETERINO SOTTOCUTAN   ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'MMG52','PREST_TRASFUSIONI','3',null,'EMOTRASFUSIONE                ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF43','PREST_TRASFUSIONI','3',null,'POSIZ CATETERE VENOSO PERIF   ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF39','PREST_TERAPIA_EV','3',null,'TERAPIA INIETTIVA ENDOVENOSA  ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'MMG40','PREST_TERAPIA_EV','3',null,'TERAPIA INFUS CON SORV MEDICA ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF43','PREST_TERAPIA_EV','3',null,'POSIZ CATETERE VENOSO PERIF   ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF41','PREST_TERAPIA_EV','3',null,'TERAPIA INIETTIVA ENDOV INFU  ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF36','PREST_TERAPIA_SOTCUT','3',null,'TERAPIA INIETTIVA INTRAMUSCOL ');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF37','PREST_TERAPIA_SOTCUT','3',null,'TERAPIA INIETTIVA SOTTOCUTANEA');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF38','PREST_TERAPIA_SOTCUT','3',null,'TERAPIA INIETTIVA SOTTOC INFUS');
Insert into PRESTAZ_BISOGNI (ID,PREST_COD,BISOGNO,FREQUENZA,QUANTITA,PREST_DES) values (SEQ_PRESTAZ_BISOGNI.nextVal,'INF46','PREST_GESTIONE_CVC','3',null,'GEST CATET VEN CENTR/PORTACATH');

Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'FIS101', 'CP_ARD', '3',null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'FIS16', 'CP_ARD', '3', null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'INF120', 'CP_AID', '3', null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'INF14', 'CP_AID', '-1', null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'INF140', 'CP_AID', '3', null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'INF146', 'CP_AID', '3', null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'INF147', 'CP_AID', '3', null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'INF148', 'CP_AID', '3', null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'INF15', 'CP_AID', '3', null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'INF16', 'CP_AID', '3', null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'INF17', 'CP_AID', '-1', null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'INF18', 'CP_AID', '-1', null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'INF19', 'CP_AID', '-1', null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'INF20', 'CP_AID', '-1', null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'INF36', 'CP_AID', '3', null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'INF37', 'CP_AID', '3', null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'INF39', 'CP_AID', '3', null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'INF43', 'CP_AID', '3', null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'INF44', 'CP_AID', '3', null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'INF46', 'CP_AID', '3', null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'INF53', 'CP_AID', '3', null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'INF6', 'CP_AID', '3', null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'INF7', 'CP_AID', '3', null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'INF78', 'CP_AID', '3', null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'INF80', 'CP_AID', '3', null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'INF82', 'CP_AID', '3', null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'INF84', 'CP_AID', '3', null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'INF86', 'CP_AID', '3', null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'INF9', 'CP_AID', '3', null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'MMG143', 'CP_ADP', '3', null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'MMG2', 'CP_ADP', null, null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'MMG20', 'CP_ADP', null, null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'MMG30', 'CP_ADP', null, null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'MMG36', 'CP_ADP', null, null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'MMG37', 'CP_ADP', null, null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'MMG6', 'CP_ADP', null, null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'MMG82', 'CP_ADP', null, null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'MMG86', 'CP_ADP', null, null, null);
Insert into PRESTAZ_BISOGNI (ID, PREST_COD, BISOGNO, FREQUENZA, QUANTITA, PREST_DES) VALUES (SEQ_PRESTAZ_BISOGNI.nextVal, 'MMG9', 'CP_ADP', null, null, null);

ALTER TABLE PRESTAZ_BISOGNI 
DROP COLUMN PREST_DES;
