--Tipi operatori per SINS_AS
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '01', 'Assistente sociale');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '02', 'Infermiere');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '03', 'Medico');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '04', 'Fisioterapista');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '05', 'Amministrativo');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '06', 'Ostetrico');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '07', 'Psichiatra');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '08', 'Ginecologo');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '09', 'Psicologo');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '10', 'Pediatra');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '11', 'Dietista');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '12', 'Educatore professionale');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '13', 'Fisiokinesiterapista');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '14', 'Logopedista');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '15', 'Neuropsichiatra infantile');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '16', 'OSS');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '17', 'Consulente'); 
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '18', 'Neuropsicomotricista');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '19', 'Psiconcologo');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '20', 'Chirurgo');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '25', 'Anestesista');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '30', 'Neurologo');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '35', 'Oncologo');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '40', 'Dermatologo');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '44', 'Caregiver');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '45', 'Internista');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '50', 'Fisiatra');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '51', 'Pneumologo');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '52', 'Palliativista');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '53', 'Cardiologo');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '54', 'Geriatra');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '55', 'Medico CRI');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '56', 'Consulente legale');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '57', 'Mediatore culturale');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '60', 'Altra figura professionale');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '65', 'Guardia medica');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '70', 'Terapista occupazionale');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '71', 'Sociologo');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '72', 'Puericultore');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '98', 'Medico specialista');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'ALL', '99', 'MMG/PLS');
--INIZIO A DEFINIRE SOTTINSIEMI PER SINS_AS
--KEY_SUBSET: SOOPCOIN
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'SOOPCOIN', '01', 'Assistente sociale');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'SOOPCOIN', '02', 'Infermiere');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'SOOPCOIN', '03', 'Medico');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'SOOPCOIN', '04', 'Fisioterapista');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'SOOPCOIN', '09', 'Psicologo');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'SOOPCOIN', '11', 'Dietista');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'SOOPCOIN', '14', 'Logopedista');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'SOOPCOIN', '16', 'OSS');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'SOOPCOIN', '20', 'Chirurgo');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'SOOPCOIN', '25', 'Anestesista');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'SOOPCOIN', '30', 'Neurologo');   
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'SOOPCOIN', '35', 'Oncologo');   
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'SOOPCOIN', '40', 'Dermatologo');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'SOOPCOIN', '45', 'Internista');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'SOOPCOIN', '50', 'Fisiatra');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'SOOPCOIN', '51', 'Pneumologo');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'SOOPCOIN', '52', 'Palliativista');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'SOOPCOIN', '53', 'Cardiologo');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'SOOPCOIN', '54', 'Geriatra');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'SOOPCOIN', '65', 'Guardia medica');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'SOOPCOIN', '70', 'Terapista occupazionale');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'SOOPCOIN', '99', 'MMG/PLS');
--KEY_SUBSET: SOOPPRVS
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'SOOPPRVS', '01', 'Assistente sociale');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'SOOPPRVS', '02', 'Infermiere');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'SOOPPRVS', '04', 'Fisioterapista');
--KEY_SUBSET: OPPREUVI
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'OPPREUVI', '01', 'Assistente sociale');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'OPPREUVI', '02', 'Infermiere coordinatore');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'OPPREUVI', '03', 'Medico di assistenza distrettuale');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'OPPREUVI', '98', 'Medico specialista');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'OPPREUVI', '99', 'MMG/PLS');
--KEY_SUBSET: CONTCHIU chiusura contatti aperti
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'CONTCHIU', '01', 'Assistente sociale');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'CONTCHIU', '02', 'Infermiere');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'CONTCHIU', '03', 'Medico');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'CONTCHIU', '04', 'Fisioterapista');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'CONTCHIU', '09', 'Psicologo');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'CONTCHIU', '11', 'Dietista');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'CONTCHIU', '14', 'Logopedista');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'CONTCHIU', '16', 'OSS');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'CONTCHIU', '20', 'Chirurgo');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'CONTCHIU', '25', 'Anestesista');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'CONTCHIU', '30', 'Neurologo');   
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'CONTCHIU', '35', 'Oncologo');   
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'CONTCHIU', '40', 'Dermatologo');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'CONTCHIU', '45', 'Internista');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'CONTCHIU', '50', 'Fisiatra');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'CONTCHIU', '51', 'Pneumologo');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'CONTCHIU', '52', 'Palliativista');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'CONTCHIU', '53', 'Cardiologo');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'CONTCHIU', '54', 'Geriatra');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'CONTCHIU', '65', 'Guardia medica');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'CONTCHIU', '70', 'Terapista occupazionale');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'CONTCHIU', '99', 'MMG/PLS');
--KEY_SUBSET: REFOPCHN tipo operaratore per combio contatto referente 
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'REFOPCHN', '01', 'Assistente sociale');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'REFOPCHN', '02', 'Infermiere');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'REFOPCHN', '03', 'Medico');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'REFOPCHN', '04', 'Fisioterapista');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'REFOPCHN', '09', 'Psicologo');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'REFOPCHN', '11', 'Dietista');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'REFOPCHN', '14', 'Logopedista');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'REFOPCHN', '16', 'OSS');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'REFOPCHN', '20', 'Chirurgo');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'REFOPCHN', '25', 'Anestesista');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'REFOPCHN', '30', 'Neurologo');   
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'REFOPCHN', '35', 'Oncologo');   
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'REFOPCHN', '40', 'Dermatologo');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'REFOPCHN', '45', 'Internista');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'REFOPCHN', '50', 'Fisiatra');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'REFOPCHN', '51', 'Pneumologo');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'REFOPCHN', '52', 'Palliativista');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'REFOPCHN', '53', 'Cardiologo');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'REFOPCHN', '54', 'Geriatra');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'REFOPCHN', '65', 'Guardia medica');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'REFOPCHN', '70', 'Terapista occupazionale');
Insert into OPERTIPO (ISAS_KPROC, KEY_SUBSET, COD_TIPO, DESC_TIPO) Values ('SINS_AS', 'REFOPCHN', '99', 'MMG/PLS');


COMMIT;
