SET DEFINE ON;  
DEFINE n_max_schede = "(SELECT (MAX(id_scheda)+1) FROM tab_schede)";


--NUOVA SCALA DI VALUTAZIONE: DISABILITA' COMUNICATIVA 
CREATE TABLE SC_DISABILITA
(
  N_CARTELLA      		NUMBER(13)   NOT NULL,
  DATA            		DATE         NOT NULL,
  DATA_TEST       		DATE,
  DATA_SCHEDA     		DATE,
  COD_OPERATORE   		CHAR(10 BYTE),
  NOME                  VARCHAR2(200 BYTE),
  TEMPO_T         		NUMBER(13),
  DISABILITA       		CHAR(1 BYTE),
  SC_DIS_PUNT			NUMBER(13),
  JDBINTERF_VERSION		NUMBER(13),
  JDBINTERF_LASTCNG		DATE,
  PRIMARY KEY (N_CARTELLA, DATA)
);
Insert into TAB_SCHEDE_CONT (ID_SCHEDA,SC_TIPO_OP,JDBINTERF_LASTCNG,JDBINTERF_VERSION) values (&n_max_schede,'00',null,null);
Insert into TAB_SCHEDE_CONT (ID_SCHEDA,SC_TIPO_OP,JDBINTERF_LASTCNG,JDBINTERF_VERSION) values (&n_max_schede,'04',null,null);
Insert into TAB_SCHEDE (ID_SCHEDA,DESCRIZIONE,TABELLA,CAMPO_PUNTEGGIO,CAMPO_DATA,CAMPO_NOME,CLASSE,FL_PUNTEGGIO,FL_ATTIVO,JDBINTERF_LASTCNG,JDBINTERF_VERSION) values (&n_max_schede,'DISABILITA'' COMUNICATIVA','sc_disabilita','sc_dis_punt','sc_dis_data','sc_dis_nome','ScalaDisabilitaComFormCtrl','S','S',null,null);



--NUOVA SCALA DI VALUTAZIONE: BARTHEL INDEX MODIFICATO (BIM) 
CREATE TABLE SC_BIM
(
  N_CARTELLA      		NUMBER(13)   NOT NULL,
  DATA            		DATE         NOT NULL,
  DATA_TEST       		DATE,
  DATA_SCHEDA     		DATE,
  COD_OPERATORE   		CHAR(10 BYTE),
  NOME                  VARCHAR2(200 BYTE),
  TEMPO_T         		NUMBER(13),
  ALIMENTAZIONE       	CHAR(2 BYTE),
  IGIENE 	        	CHAR(2 BYTE),
  BAGNO	        	    CHAR(2 BYTE),
  ABBIGLIAMENTO			CHAR(2 BYTE),
  TRASFERIMENTI			CHAR(2 BYTE),
  USO_WC 		        CHAR(2 BYTE),
  URINARIA			    CHAR(2 BYTE),
  INTESTINALE			CHAR(2 BYTE),
  DEAMBULA			    CHAR(2 BYTE),
  CARROZZINA			CHAR(2 BYTE),
  SCALE			        CHAR(2 BYTE),
  SC_BIM_PUNT			NUMBER(13),
  LIV_DIPENDENZA		VARCHAR2(200 BYTE),
  ORE_ASSISTENZA		VARCHAR2(200 BYTE),
  JDBINTERF_VERSION		NUMBER(13),
  JDBINTERF_LASTCNG		DATE,
  PRIMARY KEY (N_CARTELLA, DATA)
);
Insert into TAB_SCHEDE_CONT (ID_SCHEDA,SC_TIPO_OP,JDBINTERF_LASTCNG,JDBINTERF_VERSION) values (&n_max_schede,'00',null,null);
Insert into TAB_SCHEDE_CONT (ID_SCHEDA,SC_TIPO_OP,JDBINTERF_LASTCNG,JDBINTERF_VERSION) values (&n_max_schede,'04',null,null);
Insert into TAB_SCHEDE (ID_SCHEDA,DESCRIZIONE,TABELLA,CAMPO_PUNTEGGIO,CAMPO_DATA,CAMPO_NOME,CLASSE,FL_PUNTEGGIO,FL_ATTIVO,JDBINTERF_LASTCNG,JDBINTERF_VERSION) values (&n_max_schede,'Barthel Index Modificato (BIM)','sc_bim','sc_bim_punt','sc_bim_data','sc_bim_nome','ScalaBarthelIndexModFormCtrl','S','S',null,null);

--NUOVA SCALA DI VALUTAZIONE: FIM
CREATE TABLE SC_FIM
(
  N_CARTELLA      		NUMBER(13)   NOT NULL,
  DATA            		DATE         NOT NULL,
  DATA_TEST       		DATE,
  DATA_SCHEDA     		DATE,
  COD_OPERATORE   		CHAR(10 BYTE),
  NOME                  VARCHAR2(200 BYTE),
  TEMPO_T         		NUMBER(13),
  NUTRIRSI_I       		CHAR(1 BYTE),
  NUTRIRSI_D       		CHAR(1 BYTE),
  NUTRIRSI_F       		CHAR(1 BYTE),
  RASSETTARSI_I       		CHAR(1 BYTE),
  RASSETTARSI_D       		CHAR(1 BYTE),
  RASSETTARSI_F       		CHAR(1 BYTE),
  LAVARSI_I       		CHAR(1 BYTE),
  LAVARSI_D       		CHAR(1 BYTE),
  LAVARSI_F       		CHAR(1 BYTE),
  VESTIRSI_SU_I       		CHAR(1 BYTE),
  VESTIRSI_SU_D       		CHAR(1 BYTE),
  VESTIRSI_SU_F       		CHAR(1 BYTE),
  VESTIRSI_GIU_I       		CHAR(1 BYTE),
  VESTIRSI_GIU_D       		CHAR(1 BYTE),
  VESTIRSI_GIU_F       		CHAR(1 BYTE),
  IGIENE_I       		CHAR(1 BYTE),
  IGIENE_D       		CHAR(1 BYTE),
  IGIENE_F       		CHAR(1 BYTE),
  VESCICA_I       		CHAR(1 BYTE),
  VESCICA_D       		CHAR(1 BYTE),
  VESCICA_F       		CHAR(1 BYTE),
  LETTO_I       		CHAR(1 BYTE),
  LETTO_D       		CHAR(1 BYTE),
  LETTO_F       		CHAR(1 BYTE),
  WC_I       		CHAR(1 BYTE),
  WC_D       		CHAR(1 BYTE),
  WC_F       		CHAR(1 BYTE),
  VASCA_I       		CHAR(1 BYTE),
  VASCA_D       		CHAR(1 BYTE),
  VASCA_F       		CHAR(1 BYTE),
  CAMMINO_CM1      		CHAR(1 BYTE),
  CAMMINO_CM2      		CHAR(1 BYTE),
  CAMMINO_CM3      		CHAR(1 BYTE),
  CAMMINO_I       		CHAR(1 BYTE),
  CAMMINO_D       		CHAR(1 BYTE),
  CAMMINO_F       		CHAR(1 BYTE),
  SCALE_I       		CHAR(1 BYTE),
  SCALE_D       		CHAR(1 BYTE),
  SCALE_F       		CHAR(1 BYTE),
  ALVO_I       		CHAR(1 BYTE),
  ALVO_D       		CHAR(1 BYTE),
  ALVO_F       		CHAR(1 BYTE),
  COMPRENSIONE_UV1 CHAR(1 BYTE),
  COMPRENSIONE_UV2 CHAR(1 BYTE),
  COMPRENSIONE_UV3 CHAR(1 BYTE),
  COMPRENSIONE_I       		CHAR(1 BYTE),
  COMPRENSIONE_D       		CHAR(1 BYTE),
  COMPRENSIONE_F       		CHAR(1 BYTE),
  ESPRESSIONE_V1 CHAR(1 BYTE),
  ESPRESSIONE_V2 CHAR(1 BYTE),
  ESPRESSIONE_V3 CHAR(1 BYTE),
  ESPRESSIONE_I CHAR(1 BYTE),
  ESPRESSIONE_D CHAR(1 BYTE),
  ESPRESSIONE_F CHAR(1 BYTE),
  RAPPORTO_I CHAR(1 BYTE),
  RAPPORTO_D CHAR(1 BYTE),
  RAPPORTO_F CHAR(1 BYTE),
  SOLUZIONE_I CHAR(1 BYTE),
  SOLUZIONE_D CHAR(1 BYTE),
  SOLUZIONE_F CHAR(1 BYTE),
  MEMORIA_I CHAR(1 BYTE),
  MEMORIA_D CHAR(1 BYTE),
  MEMORIA_F CHAR(1 BYTE),
  PUNTEGGIO_I NUMBER(13),
  PUNTEGGIO_D NUMBER(13),
  PUNTEGGIO_F NUMBER(13),
  SC_DIS_PUNT			NUMBER(13),
  JDBINTERF_VERSION		NUMBER(13),
  JDBINTERF_LASTCNG		DATE,
  PRIMARY KEY (N_CARTELLA, DATA)
);

Insert into TAB_SCHEDE_CONT (ID_SCHEDA,SC_TIPO_OP,JDBINTERF_LASTCNG,JDBINTERF_VERSION) values (&n_max_schede,'00',null,null);
Insert into TAB_SCHEDE (ID_SCHEDA,DESCRIZIONE,TABELLA,CAMPO_PUNTEGGIO,CAMPO_DATA,CAMPO_NOME,CLASSE,FL_PUNTEGGIO,FL_ATTIVO,JDBINTERF_LASTCNG,JDBINTERF_VERSION) values (&n_max_schede,'SCALA FIM','sc_fim','sc_fim_punt','sc_fim_data','sc_fim_nome','ScalaFimFormCtrl','N','S',null,null);


 
COMMIT;

