UPDATE CONF SET CONF_TXT = 'Vers. 17.02' WHERE CONF_KPROC = 'SINS' AND CONF_KEY = 'VERSIONE';

--Adeguamento della tabella peratori alla presenza di operatori fittizi per l'assegnazione temporanea.
ALTER TABLE OPERATORI ADD (FLAG_FITTIZIO VARCHAR2(1) DEFAULT 'N' );

INSERT INTO CONF (CONF_KPROC, CONF_KEY, CONF_TXT, CONF_NUM, CONF_DATE, CONF_REM, JDBINTERF_VERSION, JDBINTERF_LASTCNG) 
 VALUES ('SINS', 'AG_NN_ES', '999999', null, null, 'Prefisso per prestazione non erogato', '0', sysdate);

ALTER TABLE AGENDANT_INTERV ADD (NN_ESEGUITO_MOTIVO CHAR(2) );
ALTER TABLE INTERV ADD (NN_ESEGUITO_MOTIVO CHAR(2) );

INSERT INTO TAB_VOCI (TAB_COD, TAB_VAL, TAB_DESCRIZIONE) VALUES ('AG_NN_ES', '#', 'Motivo non eseguito');
INSERT INTO TAB_VOCI (TAB_COD, TAB_VAL, TAB_DESCRIZIONE) VALUES ('AG_NN_ES', '0', 'Rifiuto');
INSERT INTO TAB_VOCI (TAB_COD, TAB_VAL, TAB_DESCRIZIONE) VALUES ('AG_NN_ES', '1', 'Assente giustificato');
INSERT INTO TAB_VOCI (TAB_COD, TAB_VAL, TAB_DESCRIZIONE) VALUES ('AG_NN_ES', '2', 'Assente ingiustificato');
INSERT INTO TAB_VOCI (TAB_COD, TAB_VAL, TAB_DESCRIZIONE) VALUES ('AG_NN_ES', '3', 'Ricoverato');
