-- Aggiornamento seguente valido solo per il database di Bolzano
INSERT INTO TBL_TAB_VOCI (TAB_COD, TAB_VAL, TAB_DESCRIZIONE, ASTER_LANG) VALUES ('AG_NN_ES', '#', 'Motivo non eseguito', 'IT');
INSERT INTO TBL_TAB_VOCI (TAB_COD, TAB_VAL, TAB_DESCRIZIONE, ASTER_LANG) VALUES ('AG_NN_ES', '0', 'Rifiuto', 'IT');
INSERT INTO TBL_TAB_VOCI (TAB_COD, TAB_VAL, TAB_DESCRIZIONE, ASTER_LANG) VALUES ('AG_NN_ES', '1', 'Assente giustificato', 'IT');
INSERT INTO TBL_TAB_VOCI (TAB_COD, TAB_VAL, TAB_DESCRIZIONE, ASTER_LANG) VALUES ('AG_NN_ES', '2', 'Assente ingiustificato', 'IT');
INSERT INTO TBL_TAB_VOCI (TAB_COD, TAB_VAL, TAB_DESCRIZIONE, ASTER_LANG) VALUES ('AG_NN_ES', '3', 'Ricoverato', 'IT');
INSERT INTO TBL_TAB_VOCI (TAB_COD, TAB_VAL, TAB_DESCRIZIONE, ASTER_LANG) VALUES ('AG_NN_ES', '#', 'Grund nicht ausgeführt', 'DE');
INSERT INTO TBL_TAB_VOCI (TAB_COD, TAB_VAL, TAB_DESCRIZIONE, ASTER_LANG) VALUES ('AG_NN_ES', '0', 'Ablehnung', 'DE');
INSERT INTO TBL_TAB_VOCI (TAB_COD, TAB_VAL, TAB_DESCRIZIONE, ASTER_LANG) VALUES ('AG_NN_ES', '1', 'Abwesend gerechtfertigt', 'DE');
INSERT INTO TBL_TAB_VOCI (TAB_COD, TAB_VAL, TAB_DESCRIZIONE, ASTER_LANG) VALUES ('AG_NN_ES', '2', 'AWOL', 'DE');
INSERT INTO TBL_TAB_VOCI (TAB_COD, TAB_VAL, TAB_DESCRIZIONE, ASTER_LANG) VALUES ('AG_NN_ES', '3', 'Hospitalisiert', 'DE');
